const sdtm_metadata = {
    RACE : "RACE",
    RACE_SPECIFICATION : "RACEOTH",
    ETHNIC : "ETHNIC",
    SDTM_TARGET: {
        "SPECIFICATION":{
            "RACE":"RACEOTH"
        }
    },
    DM: {
        STUDYID:"",
        DOMAIN:"",
        USUBJID:"",
        SUBJID:"",
        RFSTDTC:"",
        RFENDTC:"",
        // RFXSTDTC:"",
        // RFXENDTC:"",
        // RFCSTDTC:"",
        // RFCENDTC:"",
        // RFICDTC:"",
        // RFPENDTC:"",
        // DTHDTC:"",
        // DTHFL:"",
        // SITEID:"",
        INVID:"",
        INVNAM:"",
        BRTHDTC:"",
        AGE:"",
        AGEU:"",
        SEX:"",
        RACE:"",
        ETHNIC:""
    },
    VS: {
        STUDYID:"",
        DOMAIN:"",
        USUBJID:"",
        VSSEQ:"",
        // :"Perm",
        // :"Perm",
        VSTESTCD:"",
        VSTEST:"",
        VSCAT:"",
        // :"Perm",
        VSPOS:"",
        VSORRES:"",
        VSORRESU:"",
        // VSSTRESC:"",
        // VSSTRESN:"",
        // VSSTRESU:"",
        // VSSTAT:"",
        // VSREASND:"",
        VSLOC:"",
        VSLAT:"",
        // VSDIR:"",
        // VSLOBXFL:"",
        // VSBLFL:"",
        // VSDRVFL:"",
        // VSTOX:"",
        // VSTOXGR:"",
        // VSCLSIG:"",
        VISITNUM:"",
        VISIT:"",
        // VISITDY:"",
        // TAETORD:"",
        // EPOCH:"",
        VSDTC:"",
        VSDY:"",
        // VSTPT:"",
        // VSTPTNUM:"",
        // VSELTM:"",
        // VSTPTREF:"",
        // VSRFTDTC:""
    },
    VS_core: {
        STUDYID:"Req",
        DOMAIN:"Req",
        USUBJID:"Req",
        VSSEQ:"Req",
        VSGRPID:"Perm",
        VSSPID:"Perm",
        VSTESTCD:"Req",
        VSTEST:"Req",
        VSCAT:"Perm",
        VSSCAT:"Perm",
        VSPOS:"Perm",
        VSORRES:"Exp",
        VSORRESU:"Exp",
        VSSTRESC:"Exp",
        VSSTRESN:"Exp",
        VSSTRESU:"Exp",
        VSSTAT:"Perm",
        VSREASND:"Perm",
        VSLOC:"Perm",
        VSLAT:"Perm",
        VSLOBXFL:"Exp",
        VSBLFL:"Perm",
        VSDRVFL:"Perm",
        // VSTOX:"Perm",
        // VSTOXGR:"Perm",
        // VSCLSIG:"Perm",
        VISITNUM:"Exp",
        VISIT:"Perm",
        // VISITDY:"Perm",
        // TAETORD:"Perm",
        // EPOCH:"Perm",
        VSDTC:"Exp",
        VSDY:"Perm",
        VSTPT:"Perm",
        VSTPTNUM:"Perm",
        // VSELTM:"Perm",
        // VSTPTREF:"Perm",
        // VSRFTDTC:"Perm"
    }

}